### ISSUE TITLE
Do not bundle JSX syntax

### ISSUE THREAD

**Issue by OliverJAsh** [SublimeLinter/SublimeLinter-jsxhint#12]
The JSX syntax can be pulled from https://github.com/reactjs/sublime-react.

Installing both creates duplicates:
![image](https://cloud.githubusercontent.com/assets/921609/4467268/1bb653c2-48ee-11e4-990e-8f3ca3ed6007.png)

**Comment by zertosh** [comment]
Hey @STRML, we've just released https://github.com/6to5/6to5-sublime as [6to5](https://packagecontrol.io/packages/6to5) in Package Control. It shows the syntax name as "JavaScript JSX" - without parens, but we're going to change the name soon. It works with `SublimeLinter-jsxhint` already since Sublime identifies it as `javascript_jsx`, and you've got it already listed in the `syntax` list.

How do you feel about removing the existing syntax, in favor of linking to ours? We have proper ES6 and JSX support. This way we don't confuse users. (Ugh this sentence reads so shady - it's not meant to be - sorry)
