### ISSUE TITLE
Using `jshint` instead of `jsxhint`

### ISSUE THREAD

**Issue by alexbeletsky** [SublimeLinter/SublimeLinter-jsxhint#25]
Guys, thanks a lot for your amazing plugin. Unfortunately, I'm having hard times to make it work properly.

My JSX files are linted incorrectly (please see this [screen shot](https://www.dropbox.com/s/n05cxsn3gasx31f/Screenshot%202015-02-17%2012.45.47.png?dl=0)).

If I turn on SublimeLinter debugger, I see following output

```bash
SublimeLinter: jshint version query: /usr/local/bin/jshint --version 
SublimeLinter: jshint version: 2.6.0 
SublimeLinter: jshint: (>= 2.5.0) satisfied by 2.6.0 
SublimeLinter: jshint activated: /usr/local/bin/jshint 
SublimeLinter: jshint: hello.jsx ['/usr/local/bin/jshint', '--verbose', '--filename', '@', '--config', '/Users/alexanderbeletsky/Development/Projects/experiments/react2/.jshintrc', '-'] 
SublimeLinter: jshint output:
/Users/alexanderbeletsky/Development/Projects/experiments/react2/js/components/hello.jsx: line 10, col 29, Unclosed regular expression. (E015)
/Users/alexanderbeletsky/Development/Projects/experiments/react2/js/components/hello.jsx: line 10, col 29, Unrecoverable syntax error. (62% scanned). (E041)
```  

I my current setup, both linters are enabled `jshint` and `jsxhint`. If I try to turn `jshint` off (only leave `jsxhint`) there is console output at all.

My assumption that SublimeLinter is somehow missing the fact I want to use `jsxhint` for `.jsx` files.

What I'm missing?

Info: Sublime Text 3, Build 3065

**Comment by STRML** [comment]
You must select a JSX syntax type, or else SublimeLinter will not know
which linter to use. I can see from your console output that it is
activating SublimeLinter-JSHint instead of SublimeLinter-JSXHint.

Babel-Sublime (https://github.com/babel/babel-sublime) is the most
complete JSX/ES6 syntax type. Install it and switch your default syntax
for .jsx files and it will work.

**Comment by alexbeletsky** [comment]
@STRML Amazing, works as charm now.

Thanks a lot for you help and great job :)

**Comment by thedamon** [comment]
I have installed jsxhint
I have syntax set to `JavaScript (Babel)`; and set all jsx files to use it and restarted Sublime

If I run jsxhint path/to/my/file on the commandline, I get `illegal import declaration`.. which I'm not sure what that's about but at least I have jsxlint installed.

In my jsx file though it isn't using jshint:
```
`SublimeLinter: chdir not set or invalid, using /path/app/scripts 
SublimeLinter: jshint: index.jsx ['/path/.npm-packages/bin/jshint', '--verbose', '--filename', '@', '--config', '/path/.jshintrc', '-'] 
```

Really not sure the culprit here or what else to try

**Comment by STRML** [comment]
Use https://github.com/roadhump/SublimeLinter-eslint , jsxhint can't handle most es6 syntax.

**Comment by thedamon** [comment]
Ah k must be an issue w babel-sublime linting the entire file as es6 and not using Jsx anywhere, then, and the command line output makes perfect sense. Realize I mistyped there, too.. Should have said "is not using *jsxhint*" but I think whatever issue is not with this repo
